apiVersion: v1
kind: Pod
metadata:
 name: flask-app
 lables:
  app: flask-app
spec:
 containers:
  - name: flask-app
    image: nareshm5859/flask-nm-app:latest
    ports:
    - containerPort: 5500
---
apiVersion: v1
kind: Service
metadata:
 name: flask-app
spec:
 selector:
  app: flask-app
 ports:
  port: 5500
  targetPort: 5500
  - protocal: TCP
 type: ClusterIP