apiVersion: v1
kind: Pod
metadata:
 name: nginx
 lables:
  app: nginx
spec:
 containers:
  - name: nginx
    image: nareshm5859/duo-nm-nginx:v4
    imagePullPolicy: Always  
    ports:
    - containerPort: 5500
---
appVersion: v1
kind: Service
metadata:
 name: nginx
spec:
 selector:
  app: nginx
 type: LoadBalancer
 ports:
  port: 80
  targetPort: 80
  - protocal: TCP
 
