apiVersion: v1
kind: Service
metadata:
 name: flask-app
spec:
 selector:
  app: flask-app
 ports:
  port: 5500
  targetPort: 5500
  - protocol: TCP

 ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-app
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: nareshm5859/duo-falsk-app:latest
        ports:
        - containerPort: 5500